// Complete Sunflower Land Recipe & Crafting Map
// Maps cooked/crafted items to required base ingredients and coins (1,000 Coins = 1 SFL)

export const SFL_RECIPES = {
  // ==========================================
  // UTENSILS & TOOLS
  // ==========================================
  "crab pot": { "feather": 5, "wool": 3, "coins": 250 },
  "mariner pot": { "feather": 10, "merino wool": 10, "coins": 500 },
  "rod": { "wood": 3, "stone": 1, "coins": 20 },
  "pickaxe": { "wood": 3, "coins": 16 },
  "stone pickaxe": { "wood": 3, "stone": 5, "coins": 16 },
  "iron pickaxe": { "wood": 3, "iron": 5, "coins": 64 },
  "gold pickaxe": { "wood": 3, "gold": 3, "coins": 80 },
  "sand drill": { "oil /1": 1, "crimstone": 1, "wood": 3, "leather": 1 },
  "sand shovel": { "wood": 2, "stone": 1 },
  "oil drill": { "wood": 20, "leather": 10, "iron": 9 },
  "oil 50/3 harvest": { "wood": 20, "iron": 9, "leather": 10, "coins": 100 },
  "oil /1": { "oil 50/3 harvest": 0.06 },

  // ==========================================
  // CRAFTING BOX & MATERIALS
  // ==========================================
  "synthetic fibre": { "wool": 3, "oil /1": 6 },
  "timber": { "wood": 90 },
  "bee box": { "honey": 8 },
  "crimsteel": { "crimstone": 3, "iron": 3 },
  "cushion": { "feather": 9 },
  "doll": { "leather": 4, "wool": 5 },
  "hardened leather": { "leather": 9 },
  "merino cushion": { "merino wool": 9 },

  // ==========================================
  // EXOTICS & GIANT FRUITS
  // ==========================================
  "purple cauliflower": { "coins": 704 },
  "adirondack potato": { "coins": 640 },
  "chiogga": { "coins": 1920 },
  "black magic": { "coins": 5200 },
  "warty goblin pumpkin": { "coins": 400 },
  "white carrot": { "coins": 3200 },
  "golden helios": { "coins": 45000 },
  "giant orange": { "coins": 500 },
  "giant banana": { "coins": 4000 },
  "giant apple": { "coins": 1500 },

  // ==========================================
  // FISH & CRUSTACEA
  // ==========================================
  "blue crab a": { "heart leaf": 3, "crab pot": 1 },
  "lobster a": { "wild grass": 3, "crab pot": 1 },
  "hermit crab a": { "grape": 5, "crab pot": 1 },
  "shrimp": { "crimstone": 2, "crab pot": 1 },
  "mussel": { "moonfur": 1, "crab pot": 1 },
  "oyster spring": { "fish stick spring": 2, "crab pot": 1 },
  "anemone a spring": { "crab pot": 1, "fish oil spring": 2 },
  "isopod": { "crab pot": 1 },
  "sea slug": { "mariner pot": 1, "crimstone": 2 },
  "sea snail a": { "mariner pot": 1, "chewed bone": 3 },
  "garden eel a": { "mariner pot": 1, "dewberry": 3 },
  "sea grapes": { "mariner pot": 1, "lunara": 3 },
  "octopus": { "mariner pot": 1, "moonfur": 1 },
  "sea urchin spring": { "mariner pot": 1, "fish stick spring": 2 },
  "horseshoe crab spring": { "mariner pot": 1, "crab stick spring": 2 },
  "barnacle": { "mariner pot": 1 },
  "blue crab b": { "ribbon": 3, "crab pot": 1 },
  "lobster b": { "crab pot": 1, "frost pebble": 3 },
  "hermit crab b": { "crab pot": 1, "rice": 5 },
  "anemone b spring": { "crab pot": 1, "crab stick spring": 2 },
  "sea snail b": { "mariner pot": 1, "ruffroot": 3 },
  "garden eel b": { "mariner pot": 1, "duskberry": 3 },
  "horseshoe crab summer": { "mariner pot": 1, "crab stick summer": 2 },

  "red snapper": { "rod": 1, "apple": 3 },
  "olive founder": { "rod": 1 },
  "anchovy": { "rod": 1, "carrot": 1 },
  "butterflyfish": { "rod": 1 },
  "halibut": { "rod": 1 },
  "blowfish": { "rod": 1 },
  "porgy": { "rod": 1 },
  "clownfish": { "rod": 1 },
  "sea bass": { "rod": 1, "sunflower": 5 },
  "sea horse": { "rod": 1 },
  "muskellunge": { "rod": 1 },
  "mackerel": { "rod": 1 },
  "squid": { "rod": 1 },
  "moray eel": { "rod": 1 },
  "tilapia": { "rod": 1 },
  "napoleanfish": { "rod": 1 },
  "surgeonfish": { "rod": 1 },
  "zebra turkeyfish": { "rod": 1 },
  "walleye": { "rod": 1 },
  "angelfish": { "rod": 1 },
  "ray": { "rod": 1 },
  "rock blackfish": { "rod": 1 },
  "hammerhead shark": { "rod": 1 },
  "tuna": { "rod": 1, "orange": 3 },
  "mahi mahi": { "rod": 1 },
  "blue marlin": { "rod": 1 },
  "weakfish": { "rod": 1 },
  "oarfish": { "rod": 1 },
  "football fish": { "rod": 1 },
  "sunfish": { "rod": 1 },
  "cobia": { "rod": 1 },
  "barred knifejaw": { "rod": 1 },
  "trout": { "rod": 1 },
  "coelacanth": { "rod": 1 },
  "saw shark": { "rod": 1 },
  "whale shark": { "rod": 1 },
  "white shark": { "rod": 1 },
  "parrotfish": { "rod": 1 },
  "horse mackerel": { "rod": 1, "blueberry": 3 },
  "treasurecrab": { "rod": 1 },

  // ==========================================
  // FISH CHUM
  // ==========================================
  "fish stick spring": { "red snapper": 6, "olive founder": 2, "zebra turkeyfish": 2 },
  "crab stick spring": { "crab": 1, "blue crab a": 1, "hermit crab a": 1, "sea slug": 1 },
  "fish oil spring": { "tuna": 8, "weakfish": 2, "oarfish": 2 },
  "fish flake spring": { "anchovy": 4, "porgy": 2, "sea bass": 2 },
  "fish flake summer": { "anchovy": 4, "butterflyfish": 2, "sea horse": 2 },
  "fish flake autumn": { "anchovy": 4, "halibut": 2, "muskellunge": 2 },
  "fish flake winter": { "anchovy": 4, "blowfish": 2, "clownfish": 2 },
  "fish stick summer": { "red snapper": 6, "surgeonfish": 2, "tilapia": 2 },
  "fish stick autumn": { "red snapper": 6, "moray eel": 2, "napoleanfish": 2 },
  "fish stick winter": { "red snapper": 6, "walleye": 2, "angelfish": 2 },
  "crab stick summer": { "crab": 1, "mussel": 1, "isopod": 1, "sea snail a": 1 },
  "crab stick autumn": { "crab": 1, "shrimp": 1, "lobster a": 1, "barnacle": 1 },
  "crab stick winter": { "crab": 1, "oyster spring": 1, "isopod": 1, "garden eel a": 1 },
  "fish oil summer": { "tuna": 8, "cobia": 2, "sunfish": 2 },
  "fish oil autumn": { "tuna": 8, "mahi mahi": 4, "crab": 2 },
  "fish oil winter": { "tuna": 8, "blue marlin": 2, "football fish": 2 },

  // ==========================================
  // COOKED FOODS & DELI
  // ==========================================
  "apple pie": { "apple": 5, "wheat": 10, "egg": 2 },
  "beetroot cake": { "beetroot": 100, "wheat": 10, "egg": 3 },
  "cabbage cake": { "cabbage": 90, "wheat": 10, "egg": 3 },
  "carrot cake": { "carrot": 120, "wheat": 10, "egg": 3 },
  "cauliflower cake": { "cauliflower": 60, "wheat": 10, "egg": 3 },
  "cornbread": { "wheat": 5, "corn": 15, "egg": 1 },
  "eggplant cake": { "eggplant": 30, "wheat": 10, "egg": 3 },
  "honey cake": { "honey": 10, "wheat": 10, "egg": 2 },
  "lemon cheese cake": { "lemon": 20, "cheese": 5, "egg": 4 },
  "orange cake": { "orange": 5, "wheat": 10, "egg": 3 },
  "parsnip cake": { "parsnip": 45, "wheat": 10, "egg": 3 },
  "potato cake": { "potato": 500, "wheat": 10, "egg": 3 },
  "pumpkin cake": { "pumpkin": 130, "wheat": 10, "egg": 3 },
  "radish cake": { "radish": 25, "wheat": 10, "egg": 3 },
  "sunflower cake": { "sunflower": 1000, "wheat": 10, "egg": 3 },
  "wheat cake": { "wheat": 35, "egg": 3 },
  "kale & mushroom pie": { "wheat": 5, "kale": 5 },

  "blue cheese": { "cheese": 20, "blueberry": 10 },
  "blueberry jam": { "blueberry": 50 },
  "cheese": { "milk": 3 },
  "fancy fries": { "sunflower": 500, "potato": 500 },
  "fermented carrots": { "carrot": 200 },
  "honey cheddar": { "cheese": 30, "honey": 5 },
  "sauerkraut": { "cabbage": 200 },
  "shroom syrup": { "honey": 20 },

  "antipasto": { "olive": 2, "grape": 2 },
  "boiled eggs": { "egg": 10 },
  "bumpkin broth": { "carrot": 10, "cabbage": 5 },
  "cabbers n mash": { "mashed potato": 100, "cabbage": 200 },
  "fried tofu": { "soybean": 15, "sunflower": 200 },
  "kale omelette": { "egg": 40, "kale": 50 },
  "kale stew": { "kale": 100 },
  "mashed potato": { "potato": 8 },
  "pizza margherita": { "tomato": 30, "cheese": 5, "wheat": 20 },
  "popcorn": { "sunflower": 100, "corn": 50 },
  "pumpkin soup": { "pumpkin": 10 },
  "rapid roast": { "pumpkin": 400 },
  "reindeer carrot": { "carrot": 5 },
  "rhubarb tart": { "rhubarb": 30 },
  "rice bun": { "rice": 2, "wheat": 50 },

  "bumpkin ganoush": { "eggplant": 30, "potato": 50, "parsnip": 10 },
  "bumpkin roast": { "mashed potato": 200, "roast veggies": 50 },
  "bumpkin salad": { "beetroot": 20, "parsnip": 10 },
  "caprese salad": { "cheese": 10, "tomato": 25, "kale": 20 },
  "cauliflower burger": { "cauliflower": 15, "wheat": 5 },
  "club sandwich": { "sunflower": 100, "carrot": 25, "wheat": 5 },
  "fruit salad": { "apple": 1, "orange": 1, "blueberry": 1 },
  "goblins brunch": { "boiled eggs": 50, "goblins treat": 10 },
  "goblins treat": { "pumpkin": 10, "radish": 20, "cabbage": 10 },
  "pancakes": { "wheat": 10, "egg": 10, "honey": 6 },
  "roast veggies": { "cauliflower": 15, "carrot": 10 },
  "spaghettti al limone": { "wheat": 10, "lemon": 15, "cheese": 30 },
  "steamed red rice": { "rice": 3, "beetroot": 50 },
  "sunflower crunch": { "sunflower": 300 },
  "surimi rice bowl": { "rice": 1, "onion": 10 },
  "tofu scramble": { "soybean": 20, "egg": 20, "cauliflower": 10 },
  "beetroot blaze": { "beetroot": 500 },
  "creamy crab bite": { "cheese": 30, "crab stick spring": 1 },
  "crimstone infused fish oil": { "crimstone": 10 },
  "mushroom jacket potatoes": { "potato": 50 },

  // ==========================================
  // SMOOTHIES
  // ==========================================
  "apple juice": { "apple": 5 },
  "banana blast": { "banana": 10, "egg": 10 },
  "bumpkin detox": { "apple": 5, "orange": 5, "carrot": 10 },
  "carrot juice": { "carrot": 30 },
  "grape juice": { "grape": 5, "radish": 20 },
  "orange juice": { "orange": 5 },
  "power smothie": { "blueberry": 10, "kale": 5 },
  "purple smoothies": { "blueberry": 5, "cabbage": 10 },
  "quick juice": { "sunflower": 50, "pumpkin": 40 },
  "slow juice": { "grape": 10, "kale": 100 },
  "sour shake": { "lemon": 20 },
  "the lot": { "blueberry": 1, "orange": 1, "grape": 1, "apple": 1, "banana": 1 },

  // ==========================================
  // DOLLS
  // ==========================================
  "shadow doll": { "doll": 1, "obsidian": 8 },
  "sizzle doll": { "doll": 1, "synthetic fibre": 8 },
  "wooly doll": { "doll": 1, "merino wool": 8 },
  "buzz doll": { "doll": 1, "honey": 8 },
  "cluck doll": { "doll": 1, "feather": 8 },
  "crude doll": { "doll": 1, "oil /1": 8 },
  "ember doll": { "doll": 1, "crimsteel": 8 },
  "gilded doll": { "doll": 1, "gold": 8 },
  "grubby doll": { "gilded doll": 1, "ember doll": 1, "shadow doll": 1 },
  "harvest doll": { "doll": 1, "turnip": 8 },
  "juicy doll": { "doll": 1, "tomato": 8 },
  "lumber doll": { "doll": 1, "timber": 8 },
  "lunar doll": { "doll": 1, "celestine": 3, "lunara": 3, "duskberry": 2 },
  "moo doll": { "doll": 1, "leather": 8 },
  "bloom doll": { "doll": 1, "prism petal": 3, "celestial frostbloom": 2, "primula enigma": 3 },

  // ==========================================
  // COMPOST & BAIT
  // ==========================================
  "earthworm spring": { "rhubarb": 2, "carrot": 1 },
  "earthworm summer": { "zucchini": 2, "pepper": 0.4 },
  "earthworm autumn": { "yam": 3 },
  "earthworm winter": { "potato": 2, "cabbage": 0.6 },
  "grub spring": { "soybean": 1, "corn": 0.6 },
  "grub summer": { "cauliflower": 0.8, "eggplant": 0.6 },
  "grub autumn": { "broccoli": 2, "artichoke": 0.4 },
  "grub winter": { "onion": 1, "turnip": 0.4 },
  "red wiggler spring": { "blueberry": 1.6, "egg": 1 },
  "red wiggler summer": { "banana": 0.6, "eggplant": 1 },
  "red wiggler autumn": { "apple": 0.8, "tomato": 1 },
  "red wiggler winter": { "lemon": 0.6, "apple": 0.6 },

  "sprout mix spring": { "rhubarb": 0.625, "carrot": 0.3125 },
  "sprout mix summer": { "zucchini": 0.625, "pepper": 0.125 },
  "sprout mix autumn": { "yam": 0.9375 },
  "sprout mix winter": { "potato": 0.625, "cabbage": 0.1875 },
  "fruitful blend spring": { "soybean": 0.5555555556, "corn": 0.3333333333 },
  "fruitful blend summer": { "cauliflower": 0.4444444444, "eggplant": 0.3333333333 },
  "fruitful blend autumn": { "broccoli": 1.111111111, "artichoke": 0.2222222222 },
  "fruitful blend winter": { "onion": 0.5555555556, "turnip": 0.2222222222 },
  "rapid root spring": { "blueberry": 0.380952381, "egg": 0.2380952381 },
  "rapid root summer": { "banana": 0.1428571429, "eggplant": 0.2380952381 },
  "rapid root autumn": { "apple": 0.1904761905, "tomato": 0.2380952381 },
  "rapid root winter": { "lemon": 0.1428571429, "apple": 0.1428571429 }
};
